spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC&tinyInt1isBit=false"
    username: root
    password: wlgud12
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-jiniworld
  jpa:
    hibernate:
      ddl-auto: update #create-drop, update, validate, none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
    show-sql: true
  logging:
    level:
      com:
        example:
          demo: DEBUG
      org:
        springframework: DEBUG
      root: DEBUG
  jwt:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWNjbGltZS1zZWNyZXQta2V5LWFpYXJhLWthbmctamktaHlvdW5nLXRlc3Q=
#    testtesttesttesttesttesttesttesttesttesttesttest
  redis:
    port: 6379
    host: localhost
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: enVX4dwv0vbqpbsswkDc
            client-secret: Ah8WVOIUng
            client-name: Naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      springframework: DEBUG
    com:
      example:
        demo: DEBUG
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**